// Mocks generated by Mockito 5.4.4 from annotations
// in tubesavely/test/payment_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter/material.dart' as _i12;
import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tubesavely/app/data/models/download_task_model.dart' as _i11;
import 'package:tubesavely/app/data/models/payment_model.dart' as _i14;
import 'package:tubesavely/app/data/models/user_model.dart' as _i9;
import 'package:tubesavely/app/data/models/video_model.dart' as _i10;
import 'package:tubesavely/app/data/providers/api_provider.dart' as _i5;
import 'package:tubesavely/app/data/providers/storage_provider.dart' as _i8;
import 'package:tubesavely/app/services/apple_payment_service.dart' as _i4;
import 'package:tubesavely/app/services/stripe_service.dart' as _i3;
import 'package:tubesavely/app/services/video_converter_service.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetHttpClient_1 extends _i1.SmartFake implements _i2.GetHttpClient {
  _FakeGetHttpClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_2<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetSocket_4 extends _i1.SmartFake implements _i2.GetSocket {
  _FakeGetSocket_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGraphQLResponse_5<T1> extends _i1.SmartFake
    implements _i2.GraphQLResponse<T1> {
  _FakeGraphQLResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStripeService_6 extends _i1.SmartFake implements _i3.StripeService {
  _FakeStripeService_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxBool_7 extends _i1.SmartFake implements _i2.RxBool {
  _FakeRxBool_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApplePaymentService_8 extends _i1.SmartFake
    implements _i4.ApplePaymentService {
  _FakeApplePaymentService_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiProvider extends _i1.Mock implements _i5.ApiProvider {
  @override
  bool get allowAutoSignedCert => (super.noSuchMethod(
        Invocation.getter(#allowAutoSignedCert),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set allowAutoSignedCert(bool? _allowAutoSignedCert) => super.noSuchMethod(
        Invocation.setter(
          #allowAutoSignedCert,
          _allowAutoSignedCert,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get userAgent => (super.noSuchMethod(
        Invocation.getter(#userAgent),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userAgent),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userAgent),
        ),
      ) as String);

  @override
  set userAgent(String? _userAgent) => super.noSuchMethod(
        Invocation.setter(
          #userAgent,
          _userAgent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get sendUserAgent => (super.noSuchMethod(
        Invocation.getter(#sendUserAgent),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set sendUserAgent(bool? _sendUserAgent) => super.noSuchMethod(
        Invocation.setter(
          #sendUserAgent,
          _sendUserAgent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set baseUrl(String? _baseUrl) => super.noSuchMethod(
        Invocation.setter(
          #baseUrl,
          _baseUrl,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get defaultContentType => (super.noSuchMethod(
        Invocation.getter(#defaultContentType),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#defaultContentType),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#defaultContentType),
        ),
      ) as String);

  @override
  set defaultContentType(String? _defaultContentType) => super.noSuchMethod(
        Invocation.setter(
          #defaultContentType,
          _defaultContentType,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get followRedirects => (super.noSuchMethod(
        Invocation.getter(#followRedirects),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set followRedirects(bool? _followRedirects) => super.noSuchMethod(
        Invocation.setter(
          #followRedirects,
          _followRedirects,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get maxRedirects => (super.noSuchMethod(
        Invocation.getter(#maxRedirects),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set maxRedirects(int? _maxRedirects) => super.noSuchMethod(
        Invocation.setter(
          #maxRedirects,
          _maxRedirects,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get maxAuthRetries => (super.noSuchMethod(
        Invocation.getter(#maxAuthRetries),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set maxAuthRetries(int? _maxAuthRetries) => super.noSuchMethod(
        Invocation.setter(
          #maxAuthRetries,
          _maxAuthRetries,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set defaultDecoder(_i2.Decoder<dynamic>? _defaultDecoder) =>
      super.noSuchMethod(
        Invocation.setter(
          #defaultDecoder,
          _defaultDecoder,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Duration get timeout => (super.noSuchMethod(
        Invocation.getter(#timeout),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#timeout),
        ),
        returnValueForMissingStub: _FakeDuration_0(
          this,
          Invocation.getter(#timeout),
        ),
      ) as Duration);

  @override
  set timeout(Duration? _timeout) => super.noSuchMethod(
        Invocation.setter(
          #timeout,
          _timeout,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set trustedCertificates(List<_i2.TrustedCertificate>? _trustedCertificates) =>
      super.noSuchMethod(
        Invocation.setter(
          #trustedCertificates,
          _trustedCertificates,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set findProxy(String Function(Uri)? _findProxy) => super.noSuchMethod(
        Invocation.setter(
          #findProxy,
          _findProxy,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get withCredentials => (super.noSuchMethod(
        Invocation.getter(#withCredentials),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set withCredentials(bool? _withCredentials) => super.noSuchMethod(
        Invocation.setter(
          #withCredentials,
          _withCredentials,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.GetSocket> get sockets => (super.noSuchMethod(
        Invocation.getter(#sockets),
        returnValue: <_i2.GetSocket>[],
        returnValueForMissingStub: <_i2.GetSocket>[],
      ) as List<_i2.GetSocket>);

  @override
  _i2.GetHttpClient get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeGetHttpClient_1(
          this,
          Invocation.getter(#httpClient),
        ),
        returnValueForMissingStub: _FakeGetHttpClient_1(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.GetHttpClient);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set sockets(List<_i2.GetSocket>? _sockets) => super.noSuchMethod(
        Invocation.setter(
          #sockets,
          _sockets,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.Response<dynamic>> parseVideo(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseVideo,
          [url],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #parseVideo,
            [url],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #parseVideo,
            [url],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getVideoInfo(String? videoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoInfo,
          [videoId],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getVideoInfo,
            [videoId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getVideoInfo,
            [videoId],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getVideoDownloadOptions(String? videoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoDownloadOptions,
          [videoId],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getVideoDownloadOptions,
            [videoId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getVideoDownloadOptions,
            [videoId],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> register(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            name,
          ],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #register,
            [
              email,
              password,
              name,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #register,
            [
              email,
              password,
              name,
            ],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> loginWithApple(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithApple,
          [data],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #loginWithApple,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #loginWithApple,
            [data],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> loginWithGoogle(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithGoogle,
          [data],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #loginWithGoogle,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #loginWithGoogle,
            [data],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #getUserInfo,
          [],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getUserInfo,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getUserInfo,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> updateUserInfo(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserInfo,
          [data],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #updateUserInfo,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #updateUserInfo,
            [data],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getDownloadHistory() => (super.noSuchMethod(
        Invocation.method(
          #getDownloadHistory,
          [],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getDownloadHistory,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getDownloadHistory,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getSupportedPlatforms() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupportedPlatforms,
          [],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getSupportedPlatforms,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getSupportedPlatforms,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getTrendingVideos() => (super.noSuchMethod(
        Invocation.method(
          #getTrendingVideos,
          [],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getTrendingVideos,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getTrendingVideos,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getMembershipPlans() => (super.noSuchMethod(
        Invocation.method(
          #getMembershipPlans,
          [],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getMembershipPlans,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getMembershipPlans,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getPointsPackages() => (super.noSuchMethod(
        Invocation.method(
          #getPointsPackages,
          [],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getPointsPackages,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getPointsPackages,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> createOrder(
    String? packageId,
    String? paymentMethod,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [
            packageId,
            paymentMethod,
          ],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #createOrder,
            [
              packageId,
              paymentMethod,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #createOrder,
            [
              packageId,
              paymentMethod,
            ],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getOrderStatus(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderStatus,
          [orderId],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getOrderStatus,
            [orderId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getOrderStatus,
            [orderId],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> verifyPayment(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPayment,
          [data],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #verifyPayment,
            [data],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #verifyPayment,
            [data],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getTransactions() => (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getTransactions,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getTransactions,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> sendResetPasswordEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendResetPasswordEmail,
          [email],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #sendResetPasswordEmail,
            [email],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #sendResetPasswordEmail,
            [email],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getAlipayParams(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAlipayParams,
          [orderId],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getAlipayParams,
            [orderId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getAlipayParams,
            [orderId],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<dynamic>> getWechatPayParams(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWechatPayParams,
          [orderId],
        ),
        returnValue:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getWechatPayParams,
            [orderId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #getWechatPayParams,
            [orderId],
          ),
        )),
      ) as _i7.Future<_i2.Response<dynamic>>);

  @override
  _i7.Future<_i2.Response<T>> get<T>(
    String? url, {
    Map<String, String>? headers,
    String? contentType,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {
            #headers: headers,
            #contentType: contentType,
            #query: query,
            #decoder: decoder,
          },
        ),
        returnValue: _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #get,
            [url],
            {
              #headers: headers,
              #contentType: contentType,
              #query: query,
              #decoder: decoder,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #get,
            [url],
            {
              #headers: headers,
              #contentType: contentType,
              #query: query,
              #decoder: decoder,
            },
          ),
        )),
      ) as _i7.Future<_i2.Response<T>>);

  @override
  _i7.Future<_i2.Response<T>> post<T>(
    String? url,
    dynamic body, {
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            url,
            body,
          ],
          {
            #contentType: contentType,
            #headers: headers,
            #query: query,
            #decoder: decoder,
            #uploadProgress: uploadProgress,
          },
        ),
        returnValue: _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #post,
            [
              url,
              body,
            ],
            {
              #contentType: contentType,
              #headers: headers,
              #query: query,
              #decoder: decoder,
              #uploadProgress: uploadProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #post,
            [
              url,
              body,
            ],
            {
              #contentType: contentType,
              #headers: headers,
              #query: query,
              #decoder: decoder,
              #uploadProgress: uploadProgress,
            },
          ),
        )),
      ) as _i7.Future<_i2.Response<T>>);

  @override
  _i7.Future<_i2.Response<T>> put<T>(
    String? url,
    dynamic body, {
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            url,
            body,
          ],
          {
            #contentType: contentType,
            #headers: headers,
            #query: query,
            #decoder: decoder,
            #uploadProgress: uploadProgress,
          },
        ),
        returnValue: _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #put,
            [
              url,
              body,
            ],
            {
              #contentType: contentType,
              #headers: headers,
              #query: query,
              #decoder: decoder,
              #uploadProgress: uploadProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #put,
            [
              url,
              body,
            ],
            {
              #contentType: contentType,
              #headers: headers,
              #query: query,
              #decoder: decoder,
              #uploadProgress: uploadProgress,
            },
          ),
        )),
      ) as _i7.Future<_i2.Response<T>>);

  @override
  _i7.Future<_i2.Response<T>> patch<T>(
    String? url,
    dynamic body, {
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [
            url,
            body,
          ],
          {
            #contentType: contentType,
            #headers: headers,
            #query: query,
            #decoder: decoder,
            #uploadProgress: uploadProgress,
          },
        ),
        returnValue: _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #patch,
            [
              url,
              body,
            ],
            {
              #contentType: contentType,
              #headers: headers,
              #query: query,
              #decoder: decoder,
              #uploadProgress: uploadProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #patch,
            [
              url,
              body,
            ],
            {
              #contentType: contentType,
              #headers: headers,
              #query: query,
              #decoder: decoder,
              #uploadProgress: uploadProgress,
            },
          ),
        )),
      ) as _i7.Future<_i2.Response<T>>);

  @override
  _i7.Future<_i2.Response<T>> request<T>(
    String? url,
    String? method, {
    dynamic body,
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [
            url,
            method,
          ],
          {
            #body: body,
            #contentType: contentType,
            #headers: headers,
            #query: query,
            #decoder: decoder,
            #uploadProgress: uploadProgress,
          },
        ),
        returnValue: _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #request,
            [
              url,
              method,
            ],
            {
              #body: body,
              #contentType: contentType,
              #headers: headers,
              #query: query,
              #decoder: decoder,
              #uploadProgress: uploadProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #request,
            [
              url,
              method,
            ],
            {
              #body: body,
              #contentType: contentType,
              #headers: headers,
              #query: query,
              #decoder: decoder,
              #uploadProgress: uploadProgress,
            },
          ),
        )),
      ) as _i7.Future<_i2.Response<T>>);

  @override
  _i7.Future<_i2.Response<T>> delete<T>(
    String? url, {
    Map<String, String>? headers,
    String? contentType,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #contentType: contentType,
            #query: query,
            #decoder: decoder,
          },
        ),
        returnValue: _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #contentType: contentType,
              #query: query,
              #decoder: decoder,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #contentType: contentType,
              #query: query,
              #decoder: decoder,
            },
          ),
        )),
      ) as _i7.Future<_i2.Response<T>>);

  @override
  _i2.GetSocket socket(
    String? url, {
    Duration? ping = const Duration(seconds: 5),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #socket,
          [url],
          {#ping: ping},
        ),
        returnValue: _FakeGetSocket_4(
          this,
          Invocation.method(
            #socket,
            [url],
            {#ping: ping},
          ),
        ),
        returnValueForMissingStub: _FakeGetSocket_4(
          this,
          Invocation.method(
            #socket,
            [url],
            {#ping: ping},
          ),
        ),
      ) as _i2.GetSocket);

  @override
  _i7.Future<_i2.GraphQLResponse<T>> query<T>(
    String? query, {
    String? url,
    Map<String, dynamic>? variables,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [query],
          {
            #url: url,
            #variables: variables,
            #headers: headers,
          },
        ),
        returnValue:
            _i7.Future<_i2.GraphQLResponse<T>>.value(_FakeGraphQLResponse_5<T>(
          this,
          Invocation.method(
            #query,
            [query],
            {
              #url: url,
              #variables: variables,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.GraphQLResponse<T>>.value(_FakeGraphQLResponse_5<T>(
          this,
          Invocation.method(
            #query,
            [query],
            {
              #url: url,
              #variables: variables,
              #headers: headers,
            },
          ),
        )),
      ) as _i7.Future<_i2.GraphQLResponse<T>>);

  @override
  _i7.Future<_i2.GraphQLResponse<T>> mutation<T>(
    String? mutation, {
    String? url,
    Map<String, dynamic>? variables,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #mutation,
          [mutation],
          {
            #url: url,
            #variables: variables,
            #headers: headers,
          },
        ),
        returnValue:
            _i7.Future<_i2.GraphQLResponse<T>>.value(_FakeGraphQLResponse_5<T>(
          this,
          Invocation.method(
            #mutation,
            [mutation],
            {
              #url: url,
              #variables: variables,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.GraphQLResponse<T>>.value(_FakeGraphQLResponse_5<T>(
          this,
          Invocation.method(
            #mutation,
            [mutation],
            {
              #url: url,
              #variables: variables,
              #headers: headers,
            },
          ),
        )),
      ) as _i7.Future<_i2.GraphQLResponse<T>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StorageProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageProvider extends _i1.Mock implements _i8.StorageProvider {
  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<void> saveUserToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveUserToken,
          [token],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveUserInfo(_i9.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUserInfo,
          [user],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearUserData() => (super.noSuchMethod(
        Invocation.method(
          #clearUserData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveDownloadHistory(List<_i10.VideoModel>? videos) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDownloadHistory,
          [videos],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addToDownloadHistory(_i10.VideoModel? video) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToDownloadHistory,
          [video],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i10.VideoModel> getDownloadHistory() => (super.noSuchMethod(
        Invocation.method(
          #getDownloadHistory,
          [],
        ),
        returnValue: <_i10.VideoModel>[],
        returnValueForMissingStub: <_i10.VideoModel>[],
      ) as List<_i10.VideoModel>);

  @override
  _i7.Future<void> clearDownloadHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearDownloadHistory,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveDownloadTasks(List<_i11.DownloadTaskModel>? tasks) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDownloadTasks,
          [tasks],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addDownloadTask(_i11.DownloadTaskModel? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDownloadTask,
          [task],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateDownloadTask(_i11.DownloadTaskModel? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDownloadTask,
          [task],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeDownloadTask(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #removeDownloadTask,
          [taskId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i11.DownloadTaskModel> getDownloadTasks() => (super.noSuchMethod(
        Invocation.method(
          #getDownloadTasks,
          [],
        ),
        returnValue: <_i11.DownloadTaskModel>[],
        returnValueForMissingStub: <_i11.DownloadTaskModel>[],
      ) as List<_i11.DownloadTaskModel>);

  @override
  _i7.Future<void> saveThemeMode(_i12.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #saveThemeMode,
          [mode],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveSetting(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSetting,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  dynamic getSetting(
    String? key, {
    dynamic defaultValue,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #getSetting,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i7.Future<void> saveData(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  dynamic getData(
    String? key, {
    dynamic defaultValue,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #getData,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> removeData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeData,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveConversionTasks(List<_i13.ConversionTask>? tasks) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConversionTasks,
          [tasks],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addConversionTask(_i13.ConversionTask? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #addConversionTask,
          [task],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateConversionTask(_i13.ConversionTask? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConversionTask,
          [task],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeConversionTask(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #removeConversionTask,
          [taskId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i13.ConversionTask> getConversionTasks() => (super.noSuchMethod(
        Invocation.method(
          #getConversionTasks,
          [],
        ),
        returnValue: <_i13.ConversionTask>[],
        returnValueForMissingStub: <_i13.ConversionTask>[],
      ) as List<_i13.ConversionTask>);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StripeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStripeService extends _i1.Mock implements _i3.StripeService {
  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<_i3.StripeService> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<_i3.StripeService>.value(_FakeStripeService_6(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.StripeService>.value(_FakeStripeService_6(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
      ) as _i7.Future<_i3.StripeService>);

  @override
  _i7.Future<bool> isGooglePaySupported() => (super.noSuchMethod(
        Invocation.method(
          #isGooglePaySupported,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, dynamic>> createPaymentIntent({
    required int? amount,
    required String? currency,
    required String? productId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPaymentIntent,
          [],
          {
            #amount: amount,
            #currency: currency,
            #productId: productId,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<bool> processPayment(_i14.OrderModel? order) =>
      (super.noSuchMethod(
        Invocation.method(
          #processPayment,
          [order],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> processGooglePay(_i14.OrderModel? order) =>
      (super.noSuchMethod(
        Invocation.method(
          #processGooglePay,
          [order],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApplePaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApplePaymentService extends _i1.Mock
    implements _i4.ApplePaymentService {
  @override
  _i2.RxBool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: _FakeRxBool_7(
          this,
          Invocation.getter(#isAvailable),
        ),
        returnValueForMissingStub: _FakeRxBool_7(
          this,
          Invocation.getter(#isAvailable),
        ),
      ) as _i2.RxBool);

  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<_i4.ApplePaymentService> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<_i4.ApplePaymentService>.value(
            _FakeApplePaymentService_8(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i4.ApplePaymentService>.value(
            _FakeApplePaymentService_8(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
      ) as _i7.Future<_i4.ApplePaymentService>);

  @override
  _i7.Future<bool> processPayment(
    _i14.OrderModel? order, {
    dynamic Function(
      bool,
      String?,
    )? callback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processPayment,
          [order],
          {#callback: callback},
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> restorePurchases() => (super.noSuchMethod(
        Invocation.method(
          #restorePurchases,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
